# Generated by Django 4.1.4 on 2023-02-27 10:13

from django.db import migrations, models
import newapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('Createdby', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', newapp.models.customerManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Employee', models.CharField(blank=True, max_length=255, null=True)),
                ('authToken', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
