# Generated by Django 4.1.4 on 2023-02-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_client_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Createdby', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('user_id', models.ManyToManyField(to='newapp.employee')),
            ],
        ),
    ]
